# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev4+g79248fb.d20230226'
__version_tuple__ = version_tuple = (0, 1, 'dev4', 'g79248fb.d20230226')
